import 'package:flutter/material.dart';
import 'package:flex_color_scheme/flex_color_scheme.dart';

sealed class AppTheme {
  static const dialogDarkBackgroundColor = Color.fromARGB(255, 39, 71, 77);
  static const dialogLightBackgroundColor = Color.fromARGB(255, 255, 255, 255);
  static const backgroundColorForPositiveInteractables =
      Color.fromARGB(229, 57, 189, 90);
  static const backgroundColorForNegativeInteractables =
      Color.fromARGB(255, 225, 86, 86);
  static final lightTheme = FlexThemeData.light(
    colors: const FlexSchemeColor(
      primary: Color(0xff1145a4),
      primaryContainer: Color(0xffacc7f6),
      secondary: Color(0xffb61d1d),
      secondaryContainer: Color(0xffec9f9f),
      tertiary: Color(0xff376bca),
      tertiaryContainer: Color(0xffcfdbf2),
      appBarColor: Color(0xffcfdbf2),
      error: Color(0xffb00020),
    ),
    usedColors: 7,
    surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
    blendLevel: 4,
    appBarStyle: FlexAppBarStyle.background,
    bottomAppBarElevation: 1.0,
    subThemesData: const FlexSubThemesData(
      blendOnLevel: 10,
      blendOnColors: false,
      blendTextTheme: true,
      useTextTheme: true,
      useM2StyleDividerInM3: true,
      thickBorderWidth: 2.0,
      splashType: FlexSplashType.inkRipple,
      defaultRadius: 8.0,
      elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
      elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
      inputDecoratorIsFilled: false,
      inputDecoratorUnfocusedHasBorder: false,
      fabUseShape: true,
      alignedDropdown: true,
      tooltipRadius: 6,
      tooltipSchemeColor: SchemeColor.primaryContainer,
      tooltipOpacity: 0.93,
      useInputDecoratorThemeInDialogs: true,
      appBarScrolledUnderElevation: 8.0,
      tabBarDividerColor: Color(0x00000000),
      drawerElevation: 1.0,
      drawerWidth: 290.0,
      bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.secondary,
      bottomNavigationBarMutedUnselectedLabel: false,
      bottomNavigationBarSelectedIconSchemeColor: SchemeColor.secondary,
      bottomNavigationBarMutedUnselectedIcon: false,
      navigationBarSelectedLabelSchemeColor: SchemeColor.onSecondaryContainer,
      navigationBarSelectedIconSchemeColor: SchemeColor.onSecondaryContainer,
      navigationBarIndicatorSchemeColor: SchemeColor.secondaryContainer,
      navigationBarIndicatorOpacity: 1.00,
      navigationBarElevation: 1.0,
      navigationBarHeight: 72.0,
      navigationRailSelectedLabelSchemeColor: SchemeColor.onSecondaryContainer,
      navigationRailSelectedIconSchemeColor: SchemeColor.onSecondaryContainer,
      navigationRailIndicatorSchemeColor: SchemeColor.secondaryContainer,
      navigationRailIndicatorOpacity: 1.00,
    ),
    useMaterial3ErrorColors: true,
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    useMaterial3: true,
    fontFamily: 'NeverMindCompact',
  );

  static final darkTheme = FlexThemeData.dark(
    colors: const FlexSchemeColor(
      primary: Color(0xff1145a4),
      primaryContainer: Color(0xffacc7f6),
      secondary: Color(0xffb61d1d),
      secondaryContainer: Color(0xffec9f9f),
      tertiary: Color(0xff376bca),
      tertiaryContainer: Color(0xffcfdbf2),
      appBarColor: Color(0xffcfdbf2),
      error: Color(0xffb00020),
    ).defaultError.toDark(40, false),
    usedColors: 7,
    blendLevel: 4,
    appBarStyle: FlexAppBarStyle.background,
    bottomAppBarElevation: 2.0,
    subThemesData: const FlexSubThemesData(
      blendOnLevel: 20,
      blendTextTheme: true,
      useTextTheme: true,
      useM2StyleDividerInM3: true,
      splashType: FlexSplashType.inkRipple,
      defaultRadius: 8.0,
      thickBorderWidth: 2.0,
      elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
      elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
      inputDecoratorIsFilled: false,
      inputDecoratorBackgroundAlpha: 114,
      inputDecoratorBorderSchemeColor: SchemeColor.onPrimary,
      inputDecoratorUnfocusedHasBorder: false,
      fabUseShape: true,
      alignedDropdown: true,
      tooltipRadius: 6,
      tooltipSchemeColor: SchemeColor.primaryContainer,
      tooltipOpacity: 0.93,
      useInputDecoratorThemeInDialogs: true,
      tabBarDividerColor: Color(0x00000000),
      drawerElevation: 1.0,
      drawerWidth: 290.0,
      bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.secondary,
      bottomNavigationBarMutedUnselectedLabel: false,
      bottomNavigationBarSelectedIconSchemeColor: SchemeColor.secondary,
      bottomNavigationBarMutedUnselectedIcon: false,
      navigationBarSelectedLabelSchemeColor: SchemeColor.onSecondaryContainer,
      navigationBarSelectedIconSchemeColor: SchemeColor.onSecondaryContainer,
      navigationBarIndicatorSchemeColor: SchemeColor.secondaryContainer,
      navigationBarIndicatorOpacity: 1.00,
      navigationBarElevation: 1.0,
      navigationBarHeight: 72.0,
      navigationRailSelectedLabelSchemeColor: SchemeColor.onSecondaryContainer,
      navigationRailSelectedIconSchemeColor: SchemeColor.onSecondaryContainer,
      navigationRailIndicatorSchemeColor: SchemeColor.secondaryContainer,
      navigationRailIndicatorOpacity: 1.00,
    ),
    useMaterial3ErrorColors: true,
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    useMaterial3: true,
    fontFamily: 'NeverMindCompact',
  );
}
