name: medialert
description: A Flutter project for alerting users about their medications.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  easy_dynamic_theme: ^2.2.0
  app_settings: ^5.1.1
  awesome_notifications: ^0.8.2
  awesome_notifications_core: ^0.8.1
  cupertino_icons: ^1.0.2
  easy_container: ^1.0.4+1
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.1
  flutter_hooks: ^0.20.3
  flutter_riverpod: ^2.4.3
  form_builder_validators: ^9.1.0
  hooks_riverpod: ^2.4.5
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  line_icons: ^2.0.3
  local_auth: ^2.1.7
  path_provider: ^2.1.1
  riverpod: ^2.4.1
  riverpod_annotation: ^2.3.0
  state_notifier: ^1.0.0
  validators: ^3.0.0
  workmanager: ^0.5.2
  permission_handler: ^11.1.0
  flutter_native_splash: ^2.3.8

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  riverpod_generator: ^2.3.5
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path_android: "assets/images/medicine.png"
  android: true
  min_sdk_android: 21

flutter_native_splash:
  image: "assets/splash.png"
  android_12:
    image: "assets/splash_android_12.png"
    

flutter:
  uses-material-design: true
  fonts:
    - family: NeverMindCompact
      fonts:
        - asset: assets/fonts/NeverMindCompact-Regular.ttf
        - asset: assets/fonts/NeverMindCompact-Medium.ttf
        - asset: assets/fonts/NeverMindCompact-Bold.ttf
  assets:
    - assets/images/
